### ISSUE TITLE
roadhog^2.x配置webpack-bundle-analyzer

### ISSUE THREAD

**Issue by xielisi16** [tsejx/blog#10]
在roadhog^2.x怎么配置webpack-bundle-analyzer

**Comment by tsejx** [comment]
> 在roadhog^2.x怎么配置webpack-bundle-analyzer

roadhog 里内置了，在 package.json 的 scripts 中加上参数 `ANALYZE=true` 即可

```json
{
  "scripts": {
    "analyze": "ANALYZE=true roadhog build"
  }
}
```
